### ISSUE TITLE
Temperature conpensation

### ISSUE THREAD

**Issue by akshulg** [SPEC-Sensors/ULPSM#2]
Not able to understand how temperature conpensation is done. Wherr does these following constants come from - _Ah, _Al, _Tc, _Tb? How are they being used in final euqation for calculation of concentration in ppm. Also where does the equation for Temperature comes from? 
Finally, how could I get schematics for the ULPSM kit?

**Comment by dpeaslee** [comment]
Thank you for your questions. You can write to me directly at dpeaslee@spec-sensors.com
I assume you are asking about the following code

 if (t>23){
	nA = nA - _Ah*(t-_Tz); 
  }
  else{
	nA = nA - _Al*(t-_Tz);
  }
  
  float Conc = nA /_Sf*(1-_Tc*(t-_Tz));

Ah and Al are coefficients for linear compensation to approximate the exponential effects of temperature, while Tc is the linear correction to sensitivity because of temperature.
If you are trying to do air quality (i.e., CO<10 ppm, NO2/O3<100 ppb), then you may want to find new values for the Ah and Al.  For instance the following would be helpful:
I(nA) = Imeasured - Izero*exp((T-Tzero)/n)
here Izero and Tzero are simultaneous raw current and temperature measured in clean air.
For CO n is about 12, for NO2/O3 n is 90.
Please write to me directly and I can provide schematics for ULPSM.
